-- Migration script for multiple customer addresses feature
-- This script is backward compatible and preserves existing data

-- Create CUSTOMER_ADDRESS table
CREATE TABLE IF NOT EXISTS CUSTOMER_ADDRESS (
    ADDRESS_ID BIGINT NOT NULL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ADDRESS_TYPE VARCHAR(20) NOT NULL,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    COMPANY VARCHAR(100),
    ADDRESS VARCHAR(256),
    CITY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    PHONE VARCHAR(32),
    STATE_PROVINCE VARCHAR(100),
    COUNTRY_ID BIGINT,
    ZONE_ID BIGINT,
    LATITUDE VARCHAR(100),
    LONGITUDE VARCHAR(100),
    DATE_CREATED TIMESTAMP,
    DATE_MODIFIED TIMESTAMP,
    UPDT_ID VARCHAR(20),
    CONSTRAINT FK_CUSTOMER_ADDRESS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CUSTOMER_ADDRESS_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
    CONSTRAINT FK_CUSTOMER_ADDRESS_ZONE FOREIGN KEY (ZONE_ID) REFERENCES ZONE(ZONE_ID)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_ADDRESS_CUSTOMER ON CUSTOMER_ADDRESS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_ADDRESS_TYPE ON CUSTOMER_ADDRESS(ADDRESS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_ADDRESS_DEFAULT ON CUSTOMER_ADDRESS(CUSTOMER_ID, ADDRESS_TYPE, IS_DEFAULT);

-- Migrate existing billing addresses from CUSTOMER table
INSERT INTO CUSTOMER_ADDRESS (
    ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, IS_DEFAULT,
    FIRST_NAME, LAST_NAME, COMPANY, ADDRESS, CITY, POSTAL_CODE,
    PHONE, STATE_PROVINCE, COUNTRY_ID, ZONE_ID, LATITUDE, LONGITUDE,
    DATE_CREATED, DATE_MODIFIED, UPDT_ID
)
SELECT 
    NEXTVAL('SM_SEQUENCER'),
    c.CUSTOMER_ID,
    'BILLING',
    TRUE,
    COALESCE(c.BILLING_FIRST_NAME, 'Unknown'),
    COALESCE(c.BILLING_LAST_NAME, 'Unknown'),
    c.BILLING_COMPANY,
    c.BILLING_STREET_ADDRESS,
    c.BILLING_CITY,
    c.BILLING_POSTCODE,
    c.BILLING_TELEPHONE,
    c.BILLING_STATE,
    c.BILLING_COUNTRY_ID,
    c.BILLING_ZONE_ID,
    c.LATITUDE,
    c.LONGITUDE,
    c.DATE_CREATED,
    c.DATE_MODIFIED,
    c.UPDT_ID
FROM CUSTOMER c
WHERE c.BILLING_FIRST_NAME IS NOT NULL AND c.BILLING_LAST_NAME IS NOT NULL;

-- Migrate existing delivery addresses from CUSTOMER table
INSERT INTO CUSTOMER_ADDRESS (
    ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, IS_DEFAULT,
    FIRST_NAME, LAST_NAME, COMPANY, ADDRESS, CITY, POSTAL_CODE,
    PHONE, STATE_PROVINCE, COUNTRY_ID, ZONE_ID,
    DATE_CREATED, DATE_MODIFIED, UPDT_ID
)
SELECT 
    NEXTVAL('SM_SEQUENCER'),
    c.CUSTOMER_ID,
    'DELIVERY',
    TRUE,
    COALESCE(c.DELIVERY_FIRST_NAME, 'Unknown'),
    COALESCE(c.DELIVERY_LAST_NAME, 'Unknown'),
    c.DELIVERY_COMPANY,
    c.DELIVERY_STREET_ADDRESS,
    c.DELIVERY_CITY,
    c.DELIVERY_POSTCODE,
    c.DELIVERY_TELEPHONE,
    c.DELIVERY_STATE,
    c.DELIVERY_COUNTRY_ID,
    c.DELIVERY_ZONE_ID,
    c.DATE_CREATED,
    c.DATE_MODIFIED,
    c.UPDT_ID
FROM CUSTOMER c
WHERE c.DELIVERY_FIRST_NAME IS NOT NULL AND c.DELIVERY_LAST_NAME IS NOT NULL;

-- Note: The existing CUSTOMER table columns (BILLING_*, DELIVERY_*) are kept for backward compatibility
-- They can be removed in a future migration after ensuring all systems are updated
